# This is a list of python packages required for using doom effectively
name: doom
channels:
  - defaults
  - conda-forge
dependencies:
  - python
  - pip
  - ruff
  - ruff-lsp
  - prettier
  - debugpy
  - jedi
  - ipython
  - latexindent.pl
  - jupyter-lsp
  - pytest
  - apache-airflow-providers-slack
  - us
  - epiweeks
  - sodapy
  - numpy
  - pandas
  - importlib_resources
  - apache-airflow-providers-postgres
  - apache-airflow-providers-openlineage
  - apache-airflow-providers-amazon
  - python-dotenv
  # python-lsp-server and it's quasi-dependencies
  - python-lsp-server
  - rope
  - pyflakes
  - mccabe
  - pycodestyle
  - yapf
  - pip:
      - semgrep
      - basedpyright
      - jedi-language-server
